<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentsSeeder extends Seeder
{
    public function run()
    {
        DB::table('equipments')->insert([
            [
                'code' => 'EQ88899944',
                'name' => 'Máy đo tim thai cá nhân Jumper JPD-100E',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'vat' => 10,
                'country' => 'Mỹ',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737527',
                'name' => 'Máy đo nồng độ oxy máu và nhịp tim Jumper JPD-500D (LED)',
                'equipment_type_code' => 'ET002',
                'unit_code' => 'UNIT010',
                'country' => 'Việt Nam',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ84729474',
                'name' => 'Máy đo huyết áp bắp tay Jumper JPD-HA210',
                'equipment_type_code' => 'ET003',
                'unit_code' => 'UNIT007',
                'country' => 'Trung Quốc',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737521',
                'name' => 'Nhiệt kế hồng ngoại không tiếp xúc Jumper FR202',
                'equipment_type_code' => 'ET004',
                'unit_code' => 'UNIT001',
                'country' => 'Đức',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737522',
                'name' => 'Cân điện tử Beurer GS10',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Nhật Bản',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737512',
                'name' => 'Máy đo huyết áp cổ tay OMRON 6121',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Nhật Bản',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737542',
                'name' => 'MN-MDHA8712 - Máy đo huyết áp HEM-8712',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Nhật Bản',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737599',
                'name' => 'GIƯỜNG Y TẾ ĐA CHỨC NĂNG A07 (Có xe lăn tách rời)',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Nhật Bản',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737528',
                'name' => 'Giường y tế đa chức năng, model: D01-S',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Nhật Bản',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737059',
                'name' => 'TỦ Y TẾ ĐẦU GIƯỜNG - D25',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Nhật Bản',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737234',
                'name' => 'MN-KWD808I- MÁY CHÂM CỨU MODEL KWD-808-I (Yingdi – Trung Quốc)',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Trung Quốc',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'EQ85737868',
                'name' => 'Máy hiệu ứng từ YF-T08A',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'country' => 'Trung Quốc',
                'vat' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
