<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuppliersSeeder extends Seeder
{
    public function run()
    {
        DB::table('suppliers')->insert([
            [
                'code' => 'SUP001',
                'name' => 'ArtCare Medical - Công Ty Cổ Phần Thương Mại Và Dịch Vụ ArtCare',
                'contact_name' => 'Lâm Nhật Huy',
                'email' => 'lamnhathuy0393418721@gmail.com',
                'phone' => '0797291986',
                'address' => 'Tòa Vinhomes Gardenia, Hàm Nghi, Q. Nam Từ Liêm, Hà Nội HOTLINE: 0911 455 379',
                'tax_code' => '9045392332',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP002',
                'name' => 'An Phú Khang Medical Equipment - Công Ty TNHH Thương Mại An Phú Khang',
                'contact_name' => 'Lê Văn Vương',
                'email' => 'ac2.hailevan@gmail.com',
                'phone' => '0974427022',
                'address' => 'Số 2 Quách Đình Bảo, P. Tiền Phong, TP. Thái Bình, Thái Bình, Việt Nam',
                'tax_code' => '9045392332',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP003',
                'name' => 'Minh Phát Healthcare - Công Ty Cổ Phần Thương Mại Minh Phát',
                'contact_name' => 'Lữ Phát Huy',
                'email' => 'lphdev04@gmail.com',
                'phone' => '0903123456',
                'address' => 'Số 15, đường Hoàng Hoa Thám, P. Ngọc Hà, Q. Ba Đình, Hà Nội',
                'tax_code' => '9045392332',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP004',
                'name' => 'Vạn Thành Refrigeration - Công ty TNHH MTV Điện Lạnh Vạn Thành',
                'contact_name' => 'Nguyễn Quốc Huy',
                'email' => 'nguyenquochuy9602@gmail.com',
                'phone' => '0987654321',
                'address' => 'Số 10, đường Nguyễn Chí Thanh, TP. Hồ Chí Minh',
                'tax_code' => '9045392332',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP005',
                'name' => 'Phúc Tín Medical Equipment - Công ty TNHH Thiết Bị Y Tế Phúc Tín',
                'contact_name' => 'Lê Nhựt Thái',
                'email' => 'nhutthai2018@gmail.com',
                'phone' => '0912345678',
                'address' => 'Số 20, đường Lê Lợi, TP. Đà Nẵng',
                'tax_code' => '9045392332',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP006',
                'name' => 'Phương Nam Healthcare Services - Công ty TNHH Dịch Vụ Y Tế Phương Nam',
                'contact_name' => 'Lữ Phát Huy',
                'email' => 'infocontact@phuongnam.com',
                'phone' => '0911122233',
                'address' => 'Số 30, đường Trần Hưng Đạo, Quận 1, TP. Hồ Chí Minh',
                'tax_code' => '9045392332',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP007',
                'name' => 'Thịnh Phát Medical Equipment - Công Ty TNHH Thiết Bị Y Tế Thịnh Phát',
                'contact_name' => 'Nguyễn Minh Khánh',
                'email' => 'khanhthinhphat@gmail.com',
                'phone' => '0934567890',
                'address' => 'Số 40, đường Nguyễn Thị Minh Khai, Q.1, TP. Hồ Chí Minh',
                'tax_code' => '1234567890',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP008',
                'name' => 'Bách Khoa Medical Equipment - Thiết Bị Y Tế Bách Khoa',
                'contact_name' => 'Trần Thị Lan',
                'email' => 'lanbachkhoa@gmail.com',
                'phone' => '0918765432',
                'address' => 'Số 50, đường Hai Bà Trưng, Q. Hai Bà Trưng, Hà Nội',
                'tax_code' => '2345678901',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP009',
                'name' => 'Đại Phát Healthcare - Công Ty TNHH Y Tế Đại Phát',
                'contact_name' => 'Phạm Văn Duy',
                'email' => 'duydaiphat@gmail.com',
                'phone' => '0901234567',
                'address' => 'Số 60, đường Lê Văn Lương, Q.7, TP. Hồ Chí Minh',
                'tax_code' => '3456789012',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'SUP010',
                'name' => 'An Khang Medical Equipment - Thiết Bị Y Tế An Khang',
                'contact_name' => 'Nguyễn Thị Bích',
                'email' => 'bichankhang@gmail.com',
                'phone' => '0923456789',
                'address' => 'Số 70, đường Nguyễn Văn Trỗi, Q. Phú Nhuận, TP. Hồ Chí Minh',
                'tax_code' => '4567890123',
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}