<?php
return [
    'Afghanistan',
    'Áo',
    'Australia',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Bắc Triều Tiên',
    'Bỉ',
    'Bosnia và Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Campuchia',
    'Canada',
    'Cát Bà',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cộng hòa Dominica',
    'Đan Mạch',
    'Đảo Solomon',
    'Đảo Marshall',
    'Đức',
    'Đông Timor',
    'Đu-bai',
    'Ecuador',
    'El Salvador',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Pháp',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Hà Lan',
    'Haiti',
    'Hàn Quốc',
    'Hungary',
    'Ấn Độ',
    'Indonesia',
    'Irak',
    'Iran',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Lào',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Lithuania',
    'Luxembourg',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Maroc',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mông Cổ',
    'Mozambique',
    'Myanmar',
    'Na Uy',
    'Nam Phi',
    'Nam Sudan',
    'Nam Mỹ',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norfolk',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Việt Nam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
];
